### ISSUE TITLE
crash on resizing to too small size

### ISSUE THREAD

**Issue by andreasvc** [xi/cplay-ng#3]
Hi there,

I've been running into a reprodicible crash. It occurs both on my version with the original curses code, as well as your rewrite/refactored version.

Recipe: use a tiling window manager, open many windows until the cplay terminal gets too small (say 1 row or less).
cplay tries to resize itself but crashes due to not enough space.

Traceback on your code (latest commit on main):
```
Traceback (most recent call last):
  File "cplay.py", line 782, in <module>
    main()
  File "cplay.py", line 775, in main
    app.run()
  File "cplay.py", line 743, in run
    self.render(force=True)
  File "cplay.py", line 691, in render
    screen.move(i, 0)
_curses.error: wmove() returned ERR
```

Traceback on my version (latest commit of my cplay master):
```
Traceback (most recent call last):
  File "./cplay", line 1939, in main
    APP.run()
  File "./cplay", line 167, in run
    r, _w, _e = select.select(R, [], [], timeout)
  File "./cplay", line 303, in handler_resize
    self.win_root.resize()
  File "./cplay", line 342, in resize
    child.resize()
  File "./cplay", line 342, in resize
    child.resize()
  File "./cplay", line 335, in resize
    self.w = self.newwin()
  File "./cplay", line 579, in newwin
    self.parent.ypos + 2, self.parent.xpos)
error: curses function returned NULL
```

The expected behavior would be something like ignoring the resize when the terminal is too small, and then gracefully resizing again when the terminal is enlarged to a suitable size (at least 5 rows I guess...).

What do you think?

**Comment by andreasvc** [comment]
Of course I first tried to write a simple fix on my version, but each time a new exception appeared and playing exception whack-a-mole doesn't seem like a good strategy...

**Comment by xi** [comment]
Thanks for the report! I can reproduce the issue. It seems to happen once the screen has less than 4 rows.

```
Playlist                           title
---------------------------------  separator
List item 1
List item 2                        list
List item 3
===|-----------------------------  progress
Playing foo                 00:00  status
```

I guess the list can shrink to 0 rows, but cplay assumes that there is always enough space for title, separator, progress, and status.

**Comment by xi** [comment]
> Of course I first tried to write a simple fix on my version, but each time a new exception appeared and playing exception whack-a-mole doesn't seem like a good strategy...

Did you encounter other exceptions? My guess would be that there is a single exception that is raised whenever curses tries to write to a position that does not exist. Or are there other cases I am missing?

**Comment by andreasvc** [comment]
I didn't try patching your fork. With my fork, new exceptions started popping up, because simply ignoring the resize caused more issues in other places. Unfortunately I don't have experience with curses, so it would take some time to figure it out. How did you approach the curses refactoring? Your code looked quite different.

**Comment by xi** [comment]
> How did you approach the curses refactoring? Your code looked quite different.

I rewrote the whole thing for 4.0.0 and removed a lot of features. I was even considering changing the name. But it still *feels* the same so I decided to keep the name.

An important difference is that now in my version there is a single function that does all the interactions with the actual screen, while the original version does tiny updates all over the place. This is probably a trade-off between performance and simplicity.

**Comment by andreasvc** [comment]
Thanks for the update. Yes I noticed your version is drifting away more ... I'll stick with the original code base.

**Comment by xi** [comment]
> With my fork, new exceptions started popping up, because simply ignoring the resize caused more issues in other places.

I just tried wrapping a `try … excpt curses.error` around the whole main loop in your version and that seemed to work ok. I would be interested in knowing more about those other issues though.
